# Generated by Django 3.0.2 on 2020-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='btre/static/photos/%Y/%m/%d/'),
        ),
    ]
